name: parent_space_new
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get_storage: ^2.0.3
  get : ^4.3.8
  intl: ^0.19.0
  flutter_staggered_animations: ^1.0.0
  flutter_svg: ^2.0.10+1
  youtube_player_flutter: ^9.0.1
  cupertino_icons: ^1.0.6
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5
  firebase_messaging: ^14.9.4
  firebase_storage: ^11.7.7
  google_sign_in: ^6.2.1
  firebase_database: ^10.5.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/Images/
  